pipeline:
  hello:
    group: build
    image: alpine
    commands:
      - echo hello world

  kubectl:
    image: komljen/drone-kubectl-helm
    secrets: [ kubernetes_server, kubernetes_cert, kubernetes_token ]
    kubectl: "get nodes"

  docker:
    image: plugins/docker:17.05
    secrets: [ docker_username, docker_password ]
    repo: https://registry.cn-shenzhen.aliyuncs.com/callme/echoserver
    tags: ${DRONE_COMMIT_SHA}
    registry: https://registry.cn-shenzhen.aliyuncs.com/callme/
