pipeline:
  hello:
    group: build
    image: alpine
    commands:
      - echo hello
  world:
    group: build
    image: alpine
    commands:
      - echo world

  done:
    image: alpine
    commands:
      - echo done

  kubectl:
    image: komljen/drone-kubectl-helm
    secrets: [ kubernetes_server, kubernetes_cert, kubernetes_token ]
    kubectl: "get nodes"

  docker:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: huwo/echoserver
    tags: ${DRONE_COMMIT_SHA}
